AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  rust-lightning-node-rankings

  Sample SAM Template for rust-lightning-node-rankings

Globals:
  Function:
    Timeout: 3
    MemorySize: 256
    Runtime: provided.al2023

Resources:
  Table:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: NodesRankingTable
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
        - AttributeName: LSI1
          AttributeType: N
      BillingMode: PAY_PER_REQUEST
      LocalSecondaryIndexes:
        - IndexName: LSI1
          KeySchema:
            - AttributeName: PK
              KeyType: HASH
            - AttributeName: LSI1
              KeyType: RANGE
          Projection: 
            ProjectionType: ALL
            
  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: dev

  FetchNodesFunction:
    Type: AWS::Serverless::Function 
    Properties:  
      FunctionName: FetchNodesFunction
      Handler: bootstrap
      CodeUri: backend/fetch_nodes
      Events:
        GetNodes:
          Type: Api 
          Properties:
            Path: /nodes
            Method: get
            RestApiId: !Ref ApiGateway
      Policies: 
        - DynamoDBReadPolicy:
            TableName: !Ref Table
    Metadata:
      BuildMethod: rust-cargolambda 

  UpdateNodeRankingsFunction:
    Type: AWS::Serverless::Function 
    Properties:
      FunctionName: UpdateNodeRankingsFunction
      Handler: bootstrap   
      CodeUri: backend/update_node_rankings
      Events:
        ScheduledEvent:
            Type: Schedule
            Properties:
              Schedule: rate(30 minutes)
      Policies: 
        - DynamoDBWritePolicy:
            TableName: !Ref Table
    Metadata:
      BuildMethod: rust-cargolambda 

Outputs:
  Api:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/dev/"
