AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  rust-lightning-node-rankings

  Sample SAM Template for rust-lightning-node-rankings

Globals:
  Function:
    Timeout: 3
    MemorySize: 512
    Runtime: provided.al2023

Resources:
##########################################################################
#                              Dynamo Table                              #
########################################################################## 
  Table:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: NodesRankingTable
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
        - AttributeName: LSI1
          AttributeType: N
      BillingMode: PAY_PER_REQUEST
      LocalSecondaryIndexes:
        - IndexName: LSI1
          KeySchema:
            - AttributeName: PK
              KeyType: HASH
            - AttributeName: LSI1
              KeyType: RANGE
          Projection: 
            ProjectionType: ALL
            
  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: dev

  FetchNodesFunction:
    Type: AWS::Serverless::Function 
    Metadata:
      EntryPoint: fetch_nodes
      BuildMethod: rust-cargolambda 
    Properties:  
      Handler: bootstrap
      CodeUri: backend/fetch_nodes
      Events:
        GetNodes:
          Type: Api 
          Properties:
            Path: /nodes
            Method: get
            RestApiId: !Ref ApiGateway
      Policies: 
        - DynamoDBReadPolicy:
            TableName: !Ref Table

  SchedulerFunction:
    Type: AWS::Serverless::Function 
    Metadata:
      BuildMethod: rust-cargolambda 
    Properties:
      Handler: bootstrap   
      CodeUri: backend/scheduler
      Events:
        ScheduledEvent:
            Type: Schedule
            Properties:
              Schedule: rate(30 minutes)
      Policies: 
        - DynamoDBWritePolicy:
            TableName: !Ref Table

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  Api:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/dev/"
